/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/type/datetime.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../protobuf/duration";
import * as pb_1 from "google-protobuf";
export declare namespace google.type {
    class DateTime extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({
            year?: number;
            month?: number;
            day?: number;
            hours?: number;
            minutes?: number;
            seconds?: number;
            nanos?: number;
        } & (({
            utc_offset?: dependency_1.google.protobuf.Duration;
            time_zone?: never;
        } | {
            utc_offset?: never;
            time_zone?: TimeZone;
        }))));
        get year(): number;
        set year(value: number);
        get month(): number;
        set month(value: number);
        get day(): number;
        set day(value: number);
        get hours(): number;
        set hours(value: number);
        get minutes(): number;
        set minutes(value: number);
        get seconds(): number;
        set seconds(value: number);
        get nanos(): number;
        set nanos(value: number);
        get utc_offset(): dependency_1.google.protobuf.Duration;
        set utc_offset(value: dependency_1.google.protobuf.Duration);
        get has_utc_offset(): boolean;
        get time_zone(): TimeZone;
        set time_zone(value: TimeZone);
        get has_time_zone(): boolean;
        get time_offset(): "none" | "utc_offset" | "time_zone" | undefined;
        static fromObject(data: {
            year?: number;
            month?: number;
            day?: number;
            hours?: number;
            minutes?: number;
            seconds?: number;
            nanos?: number;
            utc_offset?: ReturnType<typeof dependency_1.google.protobuf.Duration.prototype.toObject>;
            time_zone?: ReturnType<typeof TimeZone.prototype.toObject>;
        }): DateTime;
        toObject(): {
            year?: number | undefined;
            month?: number | undefined;
            day?: number | undefined;
            hours?: number | undefined;
            minutes?: number | undefined;
            seconds?: number | undefined;
            nanos?: number | undefined;
            utc_offset?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
            time_zone?: {
                id?: string | undefined;
                version?: string | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DateTime;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): DateTime;
    }
    class TimeZone extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            id?: string;
            version?: string;
        });
        get id(): string;
        set id(value: string);
        get version(): string;
        set version(value: string);
        static fromObject(data: {
            id?: string;
            version?: string;
        }): TimeZone;
        toObject(): {
            id?: string | undefined;
            version?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TimeZone;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): TimeZone;
    }
}
