/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/type/latlng.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export declare namespace google.type {
    class LatLng extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            latitude?: number;
            longitude?: number;
        });
        get latitude(): number;
        set latitude(value: number);
        get longitude(): number;
        set longitude(value: number);
        static fromObject(data: {
            latitude?: number;
            longitude?: number;
        }): LatLng;
        toObject(): {
            latitude?: number | undefined;
            longitude?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LatLng;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): LatLng;
    }
}
