/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/type/localized_text.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export declare namespace google.type {
    class LocalizedText extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            text?: string;
            language_code?: string;
        });
        get text(): string;
        set text(value: string);
        get language_code(): string;
        set language_code(value: string);
        static fromObject(data: {
            text?: string;
            language_code?: string;
        }): LocalizedText;
        toObject(): {
            text?: string | undefined;
            language_code?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LocalizedText;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): LocalizedText;
    }
}
