/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/type/money.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export declare namespace google.type {
    class Money extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            currency_code?: string;
            units?: number;
            nanos?: number;
        });
        get currency_code(): string;
        set currency_code(value: string);
        get units(): number;
        set units(value: number);
        get nanos(): number;
        set nanos(value: number);
        static fromObject(data: {
            currency_code?: string;
            units?: number;
            nanos?: number;
        }): Money;
        toObject(): {
            currency_code?: string | undefined;
            units?: number | undefined;
            nanos?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Money;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Money;
    }
}
