/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/type/money.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace google.type {
    export class Money extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            currency_code?: string;
            units?: number;
            nanos?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("currency_code" in data && data.currency_code != undefined) {
                    this.currency_code = data.currency_code;
                }
                if ("units" in data && data.units != undefined) {
                    this.units = data.units;
                }
                if ("nanos" in data && data.nanos != undefined) {
                    this.nanos = data.nanos;
                }
            }
        }
        get currency_code() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set currency_code(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get units() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set units(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get nanos() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set nanos(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            currency_code?: string;
            units?: number;
            nanos?: number;
        }): Money {
            const message = new Money({});
            if (data.currency_code != null) {
                message.currency_code = data.currency_code;
            }
            if (data.units != null) {
                message.units = data.units;
            }
            if (data.nanos != null) {
                message.nanos = data.nanos;
            }
            return message;
        }
        toObject() {
            const data: {
                currency_code?: string;
                units?: number;
                nanos?: number;
            } = {};
            if (this.currency_code != null) {
                data.currency_code = this.currency_code;
            }
            if (this.units != null) {
                data.units = this.units;
            }
            if (this.nanos != null) {
                data.nanos = this.nanos;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.currency_code.length)
                writer.writeString(1, this.currency_code);
            if (this.units != 0)
                writer.writeInt64(2, this.units);
            if (this.nanos != 0)
                writer.writeInt32(3, this.nanos);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Money {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Money();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.currency_code = reader.readString();
                        break;
                    case 2:
                        message.units = reader.readInt64();
                        break;
                    case 3:
                        message.nanos = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Money {
            return Money.deserialize(bytes);
        }
    }
}
