/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/rpc/error_details.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../protobuf/duration";
import * as pb_1 from "google-protobuf";
export declare namespace google.rpc {
    class ErrorInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            reason?: string;
            domain?: string;
            metadata?: Map<string, string>;
        });
        get reason(): string;
        set reason(value: string);
        get domain(): string;
        set domain(value: string);
        get metadata(): Map<string, string>;
        set metadata(value: Map<string, string>);
        static fromObject(data: {
            reason?: string;
            domain?: string;
            metadata?: {
                [key: string]: string;
            };
        }): ErrorInfo;
        toObject(): {
            reason?: string | undefined;
            domain?: string | undefined;
            metadata?: {
                [key: string]: string;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrorInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ErrorInfo;
    }
    class RetryInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            retry_delay?: dependency_1.google.protobuf.Duration;
        });
        get retry_delay(): dependency_1.google.protobuf.Duration;
        set retry_delay(value: dependency_1.google.protobuf.Duration);
        get has_retry_delay(): boolean;
        static fromObject(data: {
            retry_delay?: ReturnType<typeof dependency_1.google.protobuf.Duration.prototype.toObject>;
        }): RetryInfo;
        toObject(): {
            retry_delay?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RetryInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RetryInfo;
    }
    class DebugInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            stack_entries?: string[];
            detail?: string;
        });
        get stack_entries(): string[];
        set stack_entries(value: string[]);
        get detail(): string;
        set detail(value: string);
        static fromObject(data: {
            stack_entries?: string[];
            detail?: string;
        }): DebugInfo;
        toObject(): {
            stack_entries?: string[] | undefined;
            detail?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DebugInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): DebugInfo;
    }
    class QuotaFailure extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            violations?: QuotaFailure.Violation[];
        });
        get violations(): QuotaFailure.Violation[];
        set violations(value: QuotaFailure.Violation[]);
        static fromObject(data: {
            violations?: ReturnType<typeof QuotaFailure.Violation.prototype.toObject>[];
        }): QuotaFailure;
        toObject(): {
            violations?: {
                subject?: string | undefined;
                description?: string | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): QuotaFailure;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): QuotaFailure;
    }
    namespace QuotaFailure {
        class Violation extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                subject?: string;
                description?: string;
            });
            get subject(): string;
            set subject(value: string);
            get description(): string;
            set description(value: string);
            static fromObject(data: {
                subject?: string;
                description?: string;
            }): Violation;
            toObject(): {
                subject?: string | undefined;
                description?: string | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Violation;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Violation;
        }
    }
    class PreconditionFailure extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            violations?: PreconditionFailure.Violation[];
        });
        get violations(): PreconditionFailure.Violation[];
        set violations(value: PreconditionFailure.Violation[]);
        static fromObject(data: {
            violations?: ReturnType<typeof PreconditionFailure.Violation.prototype.toObject>[];
        }): PreconditionFailure;
        toObject(): {
            violations?: {
                type?: string | undefined;
                subject?: string | undefined;
                description?: string | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PreconditionFailure;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): PreconditionFailure;
    }
    namespace PreconditionFailure {
        class Violation extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                type?: string;
                subject?: string;
                description?: string;
            });
            get type(): string;
            set type(value: string);
            get subject(): string;
            set subject(value: string);
            get description(): string;
            set description(value: string);
            static fromObject(data: {
                type?: string;
                subject?: string;
                description?: string;
            }): Violation;
            toObject(): {
                type?: string | undefined;
                subject?: string | undefined;
                description?: string | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Violation;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Violation;
        }
    }
    class BadRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            field_violations?: BadRequest.FieldViolation[];
        });
        get field_violations(): BadRequest.FieldViolation[];
        set field_violations(value: BadRequest.FieldViolation[]);
        static fromObject(data: {
            field_violations?: ReturnType<typeof BadRequest.FieldViolation.prototype.toObject>[];
        }): BadRequest;
        toObject(): {
            field_violations?: {
                field?: string | undefined;
                description?: string | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BadRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BadRequest;
    }
    namespace BadRequest {
        class FieldViolation extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                field?: string;
                description?: string;
            });
            get field(): string;
            set field(value: string);
            get description(): string;
            set description(value: string);
            static fromObject(data: {
                field?: string;
                description?: string;
            }): FieldViolation;
            toObject(): {
                field?: string | undefined;
                description?: string | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): FieldViolation;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): FieldViolation;
        }
    }
    class RequestInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            request_id?: string;
            serving_data?: string;
        });
        get request_id(): string;
        set request_id(value: string);
        get serving_data(): string;
        set serving_data(value: string);
        static fromObject(data: {
            request_id?: string;
            serving_data?: string;
        }): RequestInfo;
        toObject(): {
            request_id?: string | undefined;
            serving_data?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RequestInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RequestInfo;
    }
    class ResourceInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            resource_type?: string;
            resource_name?: string;
            owner?: string;
            description?: string;
        });
        get resource_type(): string;
        set resource_type(value: string);
        get resource_name(): string;
        set resource_name(value: string);
        get owner(): string;
        set owner(value: string);
        get description(): string;
        set description(value: string);
        static fromObject(data: {
            resource_type?: string;
            resource_name?: string;
            owner?: string;
            description?: string;
        }): ResourceInfo;
        toObject(): {
            resource_type?: string | undefined;
            resource_name?: string | undefined;
            owner?: string | undefined;
            description?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ResourceInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ResourceInfo;
    }
    class Help extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            links?: Help.Link[];
        });
        get links(): Help.Link[];
        set links(value: Help.Link[]);
        static fromObject(data: {
            links?: ReturnType<typeof Help.Link.prototype.toObject>[];
        }): Help;
        toObject(): {
            links?: {
                description?: string | undefined;
                url?: string | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Help;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Help;
    }
    namespace Help {
        class Link extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                description?: string;
                url?: string;
            });
            get description(): string;
            set description(value: string);
            get url(): string;
            set url(value: string);
            static fromObject(data: {
                description?: string;
                url?: string;
            }): Link;
            toObject(): {
                description?: string | undefined;
                url?: string | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Link;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Link;
        }
    }
    class LocalizedMessage extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            locale?: string;
            message?: string;
        });
        get locale(): string;
        set locale(value: string);
        get message(): string;
        set message(value: string);
        static fromObject(data: {
            locale?: string;
            message?: string;
        }): LocalizedMessage;
        toObject(): {
            locale?: string | undefined;
            message?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LocalizedMessage;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): LocalizedMessage;
    }
}
