/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/api/expr/v1alpha1/syntax.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../protobuf/duration";
import * as dependency_2 from "./../../../protobuf/struct";
import * as dependency_3 from "./../../../protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export declare namespace google.api.expr.v1alpha1 {
    class ParsedExpr extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            expr?: Expr;
            source_info?: SourceInfo;
        });
        get expr(): Expr;
        set expr(value: Expr);
        get has_expr(): boolean;
        get source_info(): SourceInfo;
        set source_info(value: SourceInfo);
        get has_source_info(): boolean;
        static fromObject(data: {
            expr?: ReturnType<typeof Expr.prototype.toObject>;
            source_info?: ReturnType<typeof SourceInfo.prototype.toObject>;
        }): ParsedExpr;
        toObject(): {
            expr?: {
                id?: number | undefined;
                const_expr?: {
                    null_value?: dependency_2.google.protobuf.NullValue | undefined;
                    bool_value?: boolean | undefined;
                    int64_value?: number | undefined;
                    uint64_value?: number | undefined;
                    double_value?: number | undefined;
                    string_value?: string | undefined;
                    bytes_value?: Uint8Array | undefined;
                    duration_value?: {
                        seconds?: number | undefined;
                        nanos?: number | undefined;
                    } | undefined;
                    timestamp_value?: {
                        seconds?: number | undefined;
                        nanos?: number | undefined;
                    } | undefined;
                } | undefined;
                ident_expr?: {
                    name?: string | undefined;
                } | undefined;
                select_expr?: {
                    operand?: any | undefined;
                    field?: string | undefined;
                    test_only?: boolean | undefined;
                } | undefined;
                call_expr?: {
                    target?: any | undefined;
                    function?: string | undefined;
                    args?: any[] | undefined;
                } | undefined;
                list_expr?: {
                    elements?: any[] | undefined;
                    optional_indices?: number[] | undefined;
                } | undefined;
                struct_expr?: {
                    message_name?: string | undefined;
                    entries?: {
                        id?: number | undefined;
                        field_key?: string | undefined;
                        map_key?: any | undefined;
                        value?: any | undefined;
                        optional_entry?: boolean | undefined;
                    }[] | undefined;
                } | undefined;
                comprehension_expr?: {
                    iter_var?: string | undefined;
                    iter_range?: any | undefined;
                    accu_var?: string | undefined;
                    accu_init?: any | undefined;
                    loop_condition?: any | undefined;
                    loop_step?: any | undefined;
                    result?: any | undefined;
                } | undefined;
            } | undefined;
            source_info?: {
                syntax_version?: string | undefined;
                location?: string | undefined;
                line_offsets?: number[] | undefined;
                positions?: {
                    [key: number]: number;
                } | undefined;
                macro_calls?: {
                    [key: number]: {
                        id?: number | undefined;
                        const_expr?: {
                            null_value?: dependency_2.google.protobuf.NullValue | undefined;
                            bool_value?: boolean | undefined;
                            int64_value?: number | undefined;
                            uint64_value?: number | undefined;
                            double_value?: number | undefined;
                            string_value?: string | undefined;
                            bytes_value?: Uint8Array | undefined;
                            duration_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                            timestamp_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                        ident_expr?: {
                            name?: string | undefined;
                        } | undefined;
                        select_expr?: {
                            operand?: any | undefined;
                            field?: string | undefined;
                            test_only?: boolean | undefined;
                        } | undefined;
                        call_expr?: {
                            target?: any | undefined;
                            function?: string | undefined;
                            args?: any[] | undefined;
                        } | undefined;
                        list_expr?: {
                            elements?: any[] | undefined;
                            optional_indices?: number[] | undefined;
                        } | undefined;
                        struct_expr?: {
                            message_name?: string | undefined;
                            entries?: {
                                id?: number | undefined;
                                field_key?: string | undefined;
                                map_key?: any | undefined;
                                value?: any | undefined;
                                optional_entry?: boolean | undefined;
                            }[] | undefined;
                        } | undefined;
                        comprehension_expr?: {
                            iter_var?: string | undefined;
                            iter_range?: any | undefined;
                            accu_var?: string | undefined;
                            accu_init?: any | undefined;
                            loop_condition?: any | undefined;
                            loop_step?: any | undefined;
                            result?: any | undefined;
                        } | undefined;
                    };
                } | undefined;
                extensions?: {
                    id?: string | undefined;
                    affected_components?: SourceInfo.Extension.Component[] | undefined;
                    version?: {
                        major?: number | undefined;
                        minor?: number | undefined;
                    } | undefined;
                }[] | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ParsedExpr;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ParsedExpr;
    }
    class Expr extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({
            id?: number;
        } & (({
            const_expr?: Constant;
            ident_expr?: never;
            select_expr?: never;
            call_expr?: never;
            list_expr?: never;
            struct_expr?: never;
            comprehension_expr?: never;
        } | {
            const_expr?: never;
            ident_expr?: Expr.Ident;
            select_expr?: never;
            call_expr?: never;
            list_expr?: never;
            struct_expr?: never;
            comprehension_expr?: never;
        } | {
            const_expr?: never;
            ident_expr?: never;
            select_expr?: Expr.Select;
            call_expr?: never;
            list_expr?: never;
            struct_expr?: never;
            comprehension_expr?: never;
        } | {
            const_expr?: never;
            ident_expr?: never;
            select_expr?: never;
            call_expr?: Expr.Call;
            list_expr?: never;
            struct_expr?: never;
            comprehension_expr?: never;
        } | {
            const_expr?: never;
            ident_expr?: never;
            select_expr?: never;
            call_expr?: never;
            list_expr?: Expr.CreateList;
            struct_expr?: never;
            comprehension_expr?: never;
        } | {
            const_expr?: never;
            ident_expr?: never;
            select_expr?: never;
            call_expr?: never;
            list_expr?: never;
            struct_expr?: Expr.CreateStruct;
            comprehension_expr?: never;
        } | {
            const_expr?: never;
            ident_expr?: never;
            select_expr?: never;
            call_expr?: never;
            list_expr?: never;
            struct_expr?: never;
            comprehension_expr?: Expr.Comprehension;
        }))));
        get id(): number;
        set id(value: number);
        get const_expr(): Constant;
        set const_expr(value: Constant);
        get has_const_expr(): boolean;
        get ident_expr(): Expr.Ident;
        set ident_expr(value: Expr.Ident);
        get has_ident_expr(): boolean;
        get select_expr(): Expr.Select;
        set select_expr(value: Expr.Select);
        get has_select_expr(): boolean;
        get call_expr(): Expr.Call;
        set call_expr(value: Expr.Call);
        get has_call_expr(): boolean;
        get list_expr(): Expr.CreateList;
        set list_expr(value: Expr.CreateList);
        get has_list_expr(): boolean;
        get struct_expr(): Expr.CreateStruct;
        set struct_expr(value: Expr.CreateStruct);
        get has_struct_expr(): boolean;
        get comprehension_expr(): Expr.Comprehension;
        set comprehension_expr(value: Expr.Comprehension);
        get has_comprehension_expr(): boolean;
        get expr_kind(): "none" | "const_expr" | "ident_expr" | "select_expr" | "call_expr" | "list_expr" | "struct_expr" | "comprehension_expr" | undefined;
        static fromObject(data: {
            id?: number;
            const_expr?: ReturnType<typeof Constant.prototype.toObject>;
            ident_expr?: ReturnType<typeof Expr.Ident.prototype.toObject>;
            select_expr?: ReturnType<typeof Expr.Select.prototype.toObject>;
            call_expr?: ReturnType<typeof Expr.Call.prototype.toObject>;
            list_expr?: ReturnType<typeof Expr.CreateList.prototype.toObject>;
            struct_expr?: ReturnType<typeof Expr.CreateStruct.prototype.toObject>;
            comprehension_expr?: ReturnType<typeof Expr.Comprehension.prototype.toObject>;
        }): Expr;
        toObject(): {
            id?: number | undefined;
            const_expr?: {
                null_value?: dependency_2.google.protobuf.NullValue | undefined;
                bool_value?: boolean | undefined;
                int64_value?: number | undefined;
                uint64_value?: number | undefined;
                double_value?: number | undefined;
                string_value?: string | undefined;
                bytes_value?: Uint8Array | undefined;
                duration_value?: {
                    seconds?: number | undefined;
                    nanos?: number | undefined;
                } | undefined;
                timestamp_value?: {
                    seconds?: number | undefined;
                    nanos?: number | undefined;
                } | undefined;
            } | undefined;
            ident_expr?: {
                name?: string | undefined;
            } | undefined;
            select_expr?: {
                operand?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: any | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                field?: string | undefined;
                test_only?: boolean | undefined;
            } | undefined;
            call_expr?: {
                target?: any | undefined;
                function?: string | undefined;
                args?: any[] | undefined;
            } | undefined;
            list_expr?: {
                elements?: any[] | undefined;
                optional_indices?: number[] | undefined;
            } | undefined;
            struct_expr?: {
                message_name?: string | undefined;
                entries?: {
                    id?: number | undefined;
                    field_key?: string | undefined;
                    map_key?: any | undefined;
                    value?: any | undefined;
                    optional_entry?: boolean | undefined;
                }[] | undefined;
            } | undefined;
            comprehension_expr?: {
                iter_var?: string | undefined;
                iter_range?: any | undefined;
                accu_var?: string | undefined;
                accu_init?: any | undefined;
                loop_condition?: any | undefined;
                loop_step?: any | undefined;
                result?: any | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Expr;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Expr;
    }
    namespace Expr {
        class Ident extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                name?: string;
            });
            get name(): string;
            set name(value: string);
            static fromObject(data: {
                name?: string;
            }): Ident;
            toObject(): {
                name?: string | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Ident;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Ident;
        }
        class Select extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                operand?: Expr;
                field?: string;
                test_only?: boolean;
            });
            get operand(): Expr;
            set operand(value: Expr);
            get has_operand(): boolean;
            get field(): string;
            set field(value: string);
            get test_only(): boolean;
            set test_only(value: boolean);
            static fromObject(data: {
                operand?: ReturnType<typeof Expr.prototype.toObject>;
                field?: string;
                test_only?: boolean;
            }): Select;
            toObject(): {
                operand?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                field?: string | undefined;
                test_only?: boolean | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Select;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Select;
        }
        class Call extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                target?: Expr;
                function?: string;
                args?: Expr[];
            });
            get target(): Expr;
            set target(value: Expr);
            get has_target(): boolean;
            get function(): string;
            set function(value: string);
            get args(): Expr[];
            set args(value: Expr[]);
            static fromObject(data: {
                target?: ReturnType<typeof Expr.prototype.toObject>;
                function?: string;
                args?: ReturnType<typeof Expr.prototype.toObject>[];
            }): Call;
            toObject(): {
                target?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                function?: string | undefined;
                args?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                }[] | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Call;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Call;
        }
        class CreateList extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                elements?: Expr[];
                optional_indices?: number[];
            });
            get elements(): Expr[];
            set elements(value: Expr[]);
            get optional_indices(): number[];
            set optional_indices(value: number[]);
            static fromObject(data: {
                elements?: ReturnType<typeof Expr.prototype.toObject>[];
                optional_indices?: number[];
            }): CreateList;
            toObject(): {
                elements?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                }[] | undefined;
                optional_indices?: number[] | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateList;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): CreateList;
        }
        class CreateStruct extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                message_name?: string;
                entries?: Expr.CreateStruct.Entry[];
            });
            get message_name(): string;
            set message_name(value: string);
            get entries(): Expr.CreateStruct.Entry[];
            set entries(value: Expr.CreateStruct.Entry[]);
            static fromObject(data: {
                message_name?: string;
                entries?: ReturnType<typeof Expr.CreateStruct.Entry.prototype.toObject>[];
            }): CreateStruct;
            toObject(): {
                message_name?: string | undefined;
                entries?: {
                    id?: number | undefined;
                    field_key?: string | undefined;
                    map_key?: {
                        id?: number | undefined;
                        const_expr?: {
                            null_value?: dependency_2.google.protobuf.NullValue | undefined;
                            bool_value?: boolean | undefined;
                            int64_value?: number | undefined;
                            uint64_value?: number | undefined;
                            double_value?: number | undefined;
                            string_value?: string | undefined;
                            bytes_value?: Uint8Array | undefined;
                            duration_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                            timestamp_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                        ident_expr?: {
                            name?: string | undefined;
                        } | undefined;
                        select_expr?: {
                            operand?: any | undefined;
                            field?: string | undefined;
                            test_only?: boolean | undefined;
                        } | undefined;
                        call_expr?: {
                            target?: any | undefined;
                            function?: string | undefined;
                            args?: any[] | undefined;
                        } | undefined;
                        list_expr?: {
                            elements?: any[] | undefined;
                            optional_indices?: number[] | undefined;
                        } | undefined;
                        struct_expr?: {
                            message_name?: string | undefined;
                            entries?: any[] | undefined;
                        } | undefined;
                        comprehension_expr?: {
                            iter_var?: string | undefined;
                            iter_range?: any | undefined;
                            accu_var?: string | undefined;
                            accu_init?: any | undefined;
                            loop_condition?: any | undefined;
                            loop_step?: any | undefined;
                            result?: any | undefined;
                        } | undefined;
                    } | undefined;
                    value?: {
                        id?: number | undefined;
                        const_expr?: {
                            null_value?: dependency_2.google.protobuf.NullValue | undefined;
                            bool_value?: boolean | undefined;
                            int64_value?: number | undefined;
                            uint64_value?: number | undefined;
                            double_value?: number | undefined;
                            string_value?: string | undefined;
                            bytes_value?: Uint8Array | undefined;
                            duration_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                            timestamp_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                        ident_expr?: {
                            name?: string | undefined;
                        } | undefined;
                        select_expr?: {
                            operand?: any | undefined;
                            field?: string | undefined;
                            test_only?: boolean | undefined;
                        } | undefined;
                        call_expr?: {
                            target?: any | undefined;
                            function?: string | undefined;
                            args?: any[] | undefined;
                        } | undefined;
                        list_expr?: {
                            elements?: any[] | undefined;
                            optional_indices?: number[] | undefined;
                        } | undefined;
                        struct_expr?: {
                            message_name?: string | undefined;
                            entries?: any[] | undefined;
                        } | undefined;
                        comprehension_expr?: {
                            iter_var?: string | undefined;
                            iter_range?: any | undefined;
                            accu_var?: string | undefined;
                            accu_init?: any | undefined;
                            loop_condition?: any | undefined;
                            loop_step?: any | undefined;
                            result?: any | undefined;
                        } | undefined;
                    } | undefined;
                    optional_entry?: boolean | undefined;
                }[] | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateStruct;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): CreateStruct;
        }
        namespace CreateStruct {
            class Entry extends pb_1.Message {
                #private;
                constructor(data?: any[] | ({
                    id?: number;
                    value?: Expr;
                    optional_entry?: boolean;
                } & (({
                    field_key?: string;
                    map_key?: never;
                } | {
                    field_key?: never;
                    map_key?: Expr;
                }))));
                get id(): number;
                set id(value: number);
                get field_key(): string;
                set field_key(value: string);
                get has_field_key(): boolean;
                get map_key(): Expr;
                set map_key(value: Expr);
                get has_map_key(): boolean;
                get value(): Expr;
                set value(value: Expr);
                get has_value(): boolean;
                get optional_entry(): boolean;
                set optional_entry(value: boolean);
                get key_kind(): "none" | "field_key" | "map_key" | undefined;
                static fromObject(data: {
                    id?: number;
                    field_key?: string;
                    map_key?: ReturnType<typeof Expr.prototype.toObject>;
                    value?: ReturnType<typeof Expr.prototype.toObject>;
                    optional_entry?: boolean;
                }): Entry;
                toObject(): {
                    id?: number | undefined;
                    field_key?: string | undefined;
                    map_key?: {
                        id?: number | undefined;
                        const_expr?: {
                            null_value?: dependency_2.google.protobuf.NullValue | undefined;
                            bool_value?: boolean | undefined;
                            int64_value?: number | undefined;
                            uint64_value?: number | undefined;
                            double_value?: number | undefined;
                            string_value?: string | undefined;
                            bytes_value?: Uint8Array | undefined;
                            duration_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                            timestamp_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                        ident_expr?: {
                            name?: string | undefined;
                        } | undefined;
                        select_expr?: {
                            operand?: any | undefined;
                            field?: string | undefined;
                            test_only?: boolean | undefined;
                        } | undefined;
                        call_expr?: {
                            target?: any | undefined;
                            function?: string | undefined;
                            args?: any[] | undefined;
                        } | undefined;
                        list_expr?: {
                            elements?: any[] | undefined;
                            optional_indices?: number[] | undefined;
                        } | undefined;
                        struct_expr?: {
                            message_name?: string | undefined;
                            entries?: {
                                id?: number | undefined;
                                field_key?: string | undefined;
                                map_key?: any | undefined;
                                value?: any | undefined;
                                optional_entry?: boolean | undefined;
                            }[] | undefined;
                        } | undefined;
                        comprehension_expr?: {
                            iter_var?: string | undefined;
                            iter_range?: any | undefined;
                            accu_var?: string | undefined;
                            accu_init?: any | undefined;
                            loop_condition?: any | undefined;
                            loop_step?: any | undefined;
                            result?: any | undefined;
                        } | undefined;
                    } | undefined;
                    value?: {
                        id?: number | undefined;
                        const_expr?: {
                            null_value?: dependency_2.google.protobuf.NullValue | undefined;
                            bool_value?: boolean | undefined;
                            int64_value?: number | undefined;
                            uint64_value?: number | undefined;
                            double_value?: number | undefined;
                            string_value?: string | undefined;
                            bytes_value?: Uint8Array | undefined;
                            duration_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                            timestamp_value?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                        ident_expr?: {
                            name?: string | undefined;
                        } | undefined;
                        select_expr?: {
                            operand?: any | undefined;
                            field?: string | undefined;
                            test_only?: boolean | undefined;
                        } | undefined;
                        call_expr?: {
                            target?: any | undefined;
                            function?: string | undefined;
                            args?: any[] | undefined;
                        } | undefined;
                        list_expr?: {
                            elements?: any[] | undefined;
                            optional_indices?: number[] | undefined;
                        } | undefined;
                        struct_expr?: {
                            message_name?: string | undefined;
                            entries?: {
                                id?: number | undefined;
                                field_key?: string | undefined;
                                map_key?: any | undefined;
                                value?: any | undefined;
                                optional_entry?: boolean | undefined;
                            }[] | undefined;
                        } | undefined;
                        comprehension_expr?: {
                            iter_var?: string | undefined;
                            iter_range?: any | undefined;
                            accu_var?: string | undefined;
                            accu_init?: any | undefined;
                            loop_condition?: any | undefined;
                            loop_step?: any | undefined;
                            result?: any | undefined;
                        } | undefined;
                    } | undefined;
                    optional_entry?: boolean | undefined;
                };
                serialize(): Uint8Array;
                serialize(w: pb_1.BinaryWriter): void;
                static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Entry;
                serializeBinary(): Uint8Array;
                static deserializeBinary(bytes: Uint8Array): Entry;
            }
        }
        class Comprehension extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                iter_var?: string;
                iter_range?: Expr;
                accu_var?: string;
                accu_init?: Expr;
                loop_condition?: Expr;
                loop_step?: Expr;
                result?: Expr;
            });
            get iter_var(): string;
            set iter_var(value: string);
            get iter_range(): Expr;
            set iter_range(value: Expr);
            get has_iter_range(): boolean;
            get accu_var(): string;
            set accu_var(value: string);
            get accu_init(): Expr;
            set accu_init(value: Expr);
            get has_accu_init(): boolean;
            get loop_condition(): Expr;
            set loop_condition(value: Expr);
            get has_loop_condition(): boolean;
            get loop_step(): Expr;
            set loop_step(value: Expr);
            get has_loop_step(): boolean;
            get result(): Expr;
            set result(value: Expr);
            get has_result(): boolean;
            static fromObject(data: {
                iter_var?: string;
                iter_range?: ReturnType<typeof Expr.prototype.toObject>;
                accu_var?: string;
                accu_init?: ReturnType<typeof Expr.prototype.toObject>;
                loop_condition?: ReturnType<typeof Expr.prototype.toObject>;
                loop_step?: ReturnType<typeof Expr.prototype.toObject>;
                result?: ReturnType<typeof Expr.prototype.toObject>;
            }): Comprehension;
            toObject(): {
                iter_var?: string | undefined;
                iter_range?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                accu_var?: string | undefined;
                accu_init?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                loop_condition?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                loop_step?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
                result?: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                } | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Comprehension;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Comprehension;
        }
    }
    class Constant extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({} & (({
            null_value?: dependency_2.google.protobuf.NullValue;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: boolean;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: number;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: number;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: number;
            string_value?: never;
            bytes_value?: never;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: string;
            bytes_value?: never;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: Uint8Array;
            duration_value?: never;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            /** @deprecated*/
            duration_value?: dependency_1.google.protobuf.Duration;
            timestamp_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            duration_value?: never;
            /** @deprecated*/
            timestamp_value?: dependency_3.google.protobuf.Timestamp;
        }))));
        get null_value(): dependency_2.google.protobuf.NullValue;
        set null_value(value: dependency_2.google.protobuf.NullValue);
        get has_null_value(): boolean;
        get bool_value(): boolean;
        set bool_value(value: boolean);
        get has_bool_value(): boolean;
        get int64_value(): number;
        set int64_value(value: number);
        get has_int64_value(): boolean;
        get uint64_value(): number;
        set uint64_value(value: number);
        get has_uint64_value(): boolean;
        get double_value(): number;
        set double_value(value: number);
        get has_double_value(): boolean;
        get string_value(): string;
        set string_value(value: string);
        get has_string_value(): boolean;
        get bytes_value(): Uint8Array;
        set bytes_value(value: Uint8Array);
        get has_bytes_value(): boolean;
        /** @deprecated*/
        get duration_value(): dependency_1.google.protobuf.Duration;
        /** @deprecated*/
        set duration_value(value: dependency_1.google.protobuf.Duration);
        /** @deprecated*/
        get has_duration_value(): boolean;
        /** @deprecated*/
        get timestamp_value(): dependency_3.google.protobuf.Timestamp;
        /** @deprecated*/
        set timestamp_value(value: dependency_3.google.protobuf.Timestamp);
        /** @deprecated*/
        get has_timestamp_value(): boolean;
        get constant_kind(): "none" | "double_value" | "string_value" | "null_value" | "bool_value" | "int64_value" | "uint64_value" | "bytes_value" | "duration_value" | "timestamp_value" | undefined;
        static fromObject(data: {
            null_value?: dependency_2.google.protobuf.NullValue;
            bool_value?: boolean;
            int64_value?: number;
            uint64_value?: number;
            double_value?: number;
            string_value?: string;
            bytes_value?: Uint8Array;
            duration_value?: ReturnType<typeof dependency_1.google.protobuf.Duration.prototype.toObject>;
            timestamp_value?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
        }): Constant;
        toObject(): {
            null_value?: dependency_2.google.protobuf.NullValue | undefined;
            bool_value?: boolean | undefined;
            int64_value?: number | undefined;
            uint64_value?: number | undefined;
            double_value?: number | undefined;
            string_value?: string | undefined;
            bytes_value?: Uint8Array | undefined;
            duration_value?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
            timestamp_value?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Constant;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Constant;
    }
    class SourceInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            syntax_version?: string;
            location?: string;
            line_offsets?: number[];
            positions?: Map<number, number>;
            macro_calls?: Map<number, Expr>;
            extensions?: SourceInfo.Extension[];
        });
        get syntax_version(): string;
        set syntax_version(value: string);
        get location(): string;
        set location(value: string);
        get line_offsets(): number[];
        set line_offsets(value: number[]);
        get positions(): Map<number, number>;
        set positions(value: Map<number, number>);
        get macro_calls(): Map<number, Expr>;
        set macro_calls(value: Map<number, Expr>);
        get extensions(): SourceInfo.Extension[];
        set extensions(value: SourceInfo.Extension[]);
        static fromObject(data: {
            syntax_version?: string;
            location?: string;
            line_offsets?: number[];
            positions?: {
                [key: number]: number;
            };
            macro_calls?: {
                [key: number]: ReturnType<typeof Expr.prototype.toObject>;
            };
            extensions?: ReturnType<typeof SourceInfo.Extension.prototype.toObject>[];
        }): SourceInfo;
        toObject(): {
            syntax_version?: string | undefined;
            location?: string | undefined;
            line_offsets?: number[] | undefined;
            positions?: {
                [key: number]: number;
            } | undefined;
            macro_calls?: {
                [key: number]: {
                    id?: number | undefined;
                    const_expr?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        duration_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                        timestamp_value?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                    ident_expr?: {
                        name?: string | undefined;
                    } | undefined;
                    select_expr?: {
                        operand?: any | undefined;
                        field?: string | undefined;
                        test_only?: boolean | undefined;
                    } | undefined;
                    call_expr?: {
                        target?: any | undefined;
                        function?: string | undefined;
                        args?: any[] | undefined;
                    } | undefined;
                    list_expr?: {
                        elements?: any[] | undefined;
                        optional_indices?: number[] | undefined;
                    } | undefined;
                    struct_expr?: {
                        message_name?: string | undefined;
                        entries?: {
                            id?: number | undefined;
                            field_key?: string | undefined;
                            map_key?: any | undefined;
                            value?: any | undefined;
                            optional_entry?: boolean | undefined;
                        }[] | undefined;
                    } | undefined;
                    comprehension_expr?: {
                        iter_var?: string | undefined;
                        iter_range?: any | undefined;
                        accu_var?: string | undefined;
                        accu_init?: any | undefined;
                        loop_condition?: any | undefined;
                        loop_step?: any | undefined;
                        result?: any | undefined;
                    } | undefined;
                };
            } | undefined;
            extensions?: {
                id?: string | undefined;
                affected_components?: SourceInfo.Extension.Component[] | undefined;
                version?: {
                    major?: number | undefined;
                    minor?: number | undefined;
                } | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SourceInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SourceInfo;
    }
    namespace SourceInfo {
        class Extension extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                id?: string;
                affected_components?: SourceInfo.Extension.Component[];
                version?: SourceInfo.Extension.Version;
            });
            get id(): string;
            set id(value: string);
            get affected_components(): SourceInfo.Extension.Component[];
            set affected_components(value: SourceInfo.Extension.Component[]);
            get version(): SourceInfo.Extension.Version;
            set version(value: SourceInfo.Extension.Version);
            get has_version(): boolean;
            static fromObject(data: {
                id?: string;
                affected_components?: SourceInfo.Extension.Component[];
                version?: ReturnType<typeof SourceInfo.Extension.Version.prototype.toObject>;
            }): Extension;
            toObject(): {
                id?: string | undefined;
                affected_components?: Extension.Component[] | undefined;
                version?: {
                    major?: number | undefined;
                    minor?: number | undefined;
                } | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Extension;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Extension;
        }
        namespace Extension {
            enum Component {
                COMPONENT_UNSPECIFIED = 0,
                COMPONENT_PARSER = 1,
                COMPONENT_TYPE_CHECKER = 2,
                COMPONENT_RUNTIME = 3
            }
            class Version extends pb_1.Message {
                #private;
                constructor(data?: any[] | {
                    major?: number;
                    minor?: number;
                });
                get major(): number;
                set major(value: number);
                get minor(): number;
                set minor(value: number);
                static fromObject(data: {
                    major?: number;
                    minor?: number;
                }): Version;
                toObject(): {
                    major?: number | undefined;
                    minor?: number | undefined;
                };
                serialize(): Uint8Array;
                serialize(w: pb_1.BinaryWriter): void;
                static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Version;
                serializeBinary(): Uint8Array;
                static deserializeBinary(bytes: Uint8Array): Version;
            }
        }
    }
    class SourcePosition extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            location?: string;
            offset?: number;
            line?: number;
            column?: number;
        });
        get location(): string;
        set location(value: string);
        get offset(): number;
        set offset(value: number);
        get line(): number;
        set line(value: number);
        get column(): number;
        set column(value: number);
        static fromObject(data: {
            location?: string;
            offset?: number;
            line?: number;
            column?: number;
        }): SourcePosition;
        toObject(): {
            location?: string | undefined;
            offset?: number | undefined;
            line?: number | undefined;
            column?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SourcePosition;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SourcePosition;
    }
}
