"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019 Google LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Value(google.protobuf.message.Message):
    """Represents a CEL value.

    This is similar to `google.protobuf.Value`, but can represent CEL's full
    range of values.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NULL_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    ENUM_VALUE_FIELD_NUMBER: builtins.int
    OBJECT_VALUE_FIELD_NUMBER: builtins.int
    MAP_VALUE_FIELD_NUMBER: builtins.int
    LIST_VALUE_FIELD_NUMBER: builtins.int
    TYPE_VALUE_FIELD_NUMBER: builtins.int
    null_value: google.protobuf.struct_pb2.NullValue.ValueType
    """Null value."""
    bool_value: builtins.bool
    """Boolean value."""
    int64_value: builtins.int
    """Signed integer value."""
    uint64_value: builtins.int
    """Unsigned integer value."""
    double_value: builtins.float
    """Floating point value."""
    string_value: builtins.str
    """UTF-8 string value."""
    bytes_value: builtins.bytes
    """Byte string value."""
    @property
    def enum_value(self) -> global___EnumValue:
        """An enum value."""
    @property
    def object_value(self) -> google.protobuf.any_pb2.Any:
        """The proto message backing an object value."""
    @property
    def map_value(self) -> global___MapValue:
        """Map value."""
    @property
    def list_value(self) -> global___ListValue:
        """List value."""
    type_value: builtins.str
    """A Type value represented by the fully qualified name of the type."""
    def __init__(
        self,
        *,
        null_value: google.protobuf.struct_pb2.NullValue.ValueType = ...,
        bool_value: builtins.bool = ...,
        int64_value: builtins.int = ...,
        uint64_value: builtins.int = ...,
        double_value: builtins.float = ...,
        string_value: builtins.str = ...,
        bytes_value: builtins.bytes = ...,
        enum_value: global___EnumValue | None = ...,
        object_value: google.protobuf.any_pb2.Any | None = ...,
        map_value: global___MapValue | None = ...,
        list_value: global___ListValue | None = ...,
        type_value: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "double_value", b"double_value", "enum_value", b"enum_value", "int64_value", b"int64_value", "kind", b"kind", "list_value", b"list_value", "map_value", b"map_value", "null_value", b"null_value", "object_value", b"object_value", "string_value", b"string_value", "type_value", b"type_value", "uint64_value", b"uint64_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "double_value", b"double_value", "enum_value", b"enum_value", "int64_value", b"int64_value", "kind", b"kind", "list_value", b"list_value", "map_value", b"map_value", "null_value", b"null_value", "object_value", b"object_value", "string_value", b"string_value", "type_value", b"type_value", "uint64_value", b"uint64_value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["kind", b"kind"]) -> typing_extensions.Literal["null_value", "bool_value", "int64_value", "uint64_value", "double_value", "string_value", "bytes_value", "enum_value", "object_value", "map_value", "list_value", "type_value"] | None: ...

global___Value = Value

@typing_extensions.final
class EnumValue(google.protobuf.message.Message):
    """An enum value."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    type: builtins.str
    """The fully qualified name of the enum type."""
    value: builtins.int
    """The value of the enum."""
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type", b"type", "value", b"value"]) -> None: ...

global___EnumValue = EnumValue

@typing_extensions.final
class ListValue(google.protobuf.message.Message):
    """A list.

    Wrapped in a message so 'not set' and empty can be differentiated, which is
    required for use in a 'oneof'.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]:
        """The ordered values in the list."""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ListValue = ListValue

@typing_extensions.final
class MapValue(google.protobuf.message.Message):
    """A map.

    Wrapped in a message so 'not set' and empty can be differentiated, which is
    required for use in a 'oneof'.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Entry(google.protobuf.message.Message):
        """An entry in the map."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        @property
        def key(self) -> global___Value:
            """The key.

            Must be unique with in the map.
            Currently only boolean, int, uint, and string values can be keys.
            """
        @property
        def value(self) -> global___Value:
            """The value."""
        def __init__(
            self,
            *,
            key: global___Value | None = ...,
            value: global___Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MapValue.Entry]:
        """The set of map entries.

        CEL has fewer restrictions on keys, so a protobuf map represenation
        cannot be used.
        """
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___MapValue.Entry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___MapValue = MapValue
