[project]
name = "speech-service-api"
version = "0.3.0"
description = "Viam modular service API that provides chat response capabilities"
authors = [
    {name = "Nick Hehr", email = "nick.hehr@viam.com"},
]
dependencies = [
    "viam-sdk>=0.13.2",
]
requires-python = ">=3.8.2,<3.13"
readme = "README.md"
license = {text = "Apache-2.0"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.resolution.overrides]
viam-sdk = "0.15.0"
grpclib = "0.4.7"

[tool.pyprojectx]
main = ["pdm"]

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "mypy-protobuf>=3.5.0",
]
