// @generated by protoc-gen-connect-es v1.6.1
// @generated from file speech.proto (package viamlabs.service.speech.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CompletionRequest, CompletionResponse, GetCommandsRequest, GetCommandsResponse, IsSpeakingRequest, IsSpeakingResponse, ListenRequest, ListenResponse, ListenTriggerRequest, ListenTriggerResponse, SayRequest, SayResponse, ToSpeechRequest, ToSpeechResponse, ToTextRequest, ToTextResponse } from "./speech_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service viamlabs.service.speech.v1.SpeechService
 */
export declare const SpeechService: {
  readonly typeName: "viamlabs.service.speech.v1.SpeechService",
  readonly methods: {
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.Say
     */
    readonly say: {
      readonly name: "Say",
      readonly I: typeof SayRequest,
      readonly O: typeof SayResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.ToText
     */
    readonly toText: {
      readonly name: "ToText",
      readonly I: typeof ToTextRequest,
      readonly O: typeof ToTextResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.ToSpeech
     */
    readonly toSpeech: {
      readonly name: "ToSpeech",
      readonly I: typeof ToSpeechRequest,
      readonly O: typeof ToSpeechResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.Completion
     */
    readonly completion: {
      readonly name: "Completion",
      readonly I: typeof CompletionRequest,
      readonly O: typeof CompletionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.GetCommands
     */
    readonly getCommands: {
      readonly name: "GetCommands",
      readonly I: typeof GetCommandsRequest,
      readonly O: typeof GetCommandsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.ListenTrigger
     */
    readonly listenTrigger: {
      readonly name: "ListenTrigger",
      readonly I: typeof ListenTriggerRequest,
      readonly O: typeof ListenTriggerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.Listen
     */
    readonly listen: {
      readonly name: "Listen",
      readonly I: typeof ListenRequest,
      readonly O: typeof ListenResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viamlabs.service.speech.v1.SpeechService.IsSpeaking
     */
    readonly isSpeaking: {
      readonly name: "IsSpeaking",
      readonly I: typeof IsSpeakingRequest,
      readonly O: typeof IsSpeakingResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

