/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 0.0.0
 * source: google/api/expr/v1beta1/value.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../protobuf/any";
import * as dependency_2 from "./../../../protobuf/struct";
import * as pb_1 from "google-protobuf";
export declare namespace google.api.expr.v1beta1 {
    class Value extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({} & (({
            null_value?: dependency_2.google.protobuf.NullValue;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: boolean;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: number;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: number;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: number;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: string;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: Uint8Array;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: EnumValue;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: dependency_1.google.protobuf.Any;
            map_value?: never;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: MapValue;
            list_value?: never;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: ListValue;
            type_value?: never;
        } | {
            null_value?: never;
            bool_value?: never;
            int64_value?: never;
            uint64_value?: never;
            double_value?: never;
            string_value?: never;
            bytes_value?: never;
            enum_value?: never;
            object_value?: never;
            map_value?: never;
            list_value?: never;
            type_value?: string;
        }))));
        get null_value(): dependency_2.google.protobuf.NullValue;
        set null_value(value: dependency_2.google.protobuf.NullValue);
        get has_null_value(): boolean;
        get bool_value(): boolean;
        set bool_value(value: boolean);
        get has_bool_value(): boolean;
        get int64_value(): number;
        set int64_value(value: number);
        get has_int64_value(): boolean;
        get uint64_value(): number;
        set uint64_value(value: number);
        get has_uint64_value(): boolean;
        get double_value(): number;
        set double_value(value: number);
        get has_double_value(): boolean;
        get string_value(): string;
        set string_value(value: string);
        get has_string_value(): boolean;
        get bytes_value(): Uint8Array;
        set bytes_value(value: Uint8Array);
        get has_bytes_value(): boolean;
        get enum_value(): EnumValue;
        set enum_value(value: EnumValue);
        get has_enum_value(): boolean;
        get object_value(): dependency_1.google.protobuf.Any;
        set object_value(value: dependency_1.google.protobuf.Any);
        get has_object_value(): boolean;
        get map_value(): MapValue;
        set map_value(value: MapValue);
        get has_map_value(): boolean;
        get list_value(): ListValue;
        set list_value(value: ListValue);
        get has_list_value(): boolean;
        get type_value(): string;
        set type_value(value: string);
        get has_type_value(): boolean;
        get kind(): "none" | "double_value" | "string_value" | "null_value" | "bool_value" | "list_value" | "int64_value" | "uint64_value" | "bytes_value" | "enum_value" | "object_value" | "map_value" | "type_value" | undefined;
        static fromObject(data: {
            null_value?: dependency_2.google.protobuf.NullValue;
            bool_value?: boolean;
            int64_value?: number;
            uint64_value?: number;
            double_value?: number;
            string_value?: string;
            bytes_value?: Uint8Array;
            enum_value?: ReturnType<typeof EnumValue.prototype.toObject>;
            object_value?: ReturnType<typeof dependency_1.google.protobuf.Any.prototype.toObject>;
            map_value?: ReturnType<typeof MapValue.prototype.toObject>;
            list_value?: ReturnType<typeof ListValue.prototype.toObject>;
            type_value?: string;
        }): Value;
        toObject(): {
            null_value?: dependency_2.google.protobuf.NullValue | undefined;
            bool_value?: boolean | undefined;
            int64_value?: number | undefined;
            uint64_value?: number | undefined;
            double_value?: number | undefined;
            string_value?: string | undefined;
            bytes_value?: Uint8Array | undefined;
            enum_value?: {
                type?: string | undefined;
                value?: number | undefined;
            } | undefined;
            object_value?: {
                type_url?: string | undefined;
                value?: Uint8Array | undefined;
            } | undefined;
            map_value?: {
                entries?: {
                    key?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        enum_value?: {
                            type?: string | undefined;
                            value?: number | undefined;
                        } | undefined;
                        object_value?: {
                            type_url?: string | undefined;
                            value?: Uint8Array | undefined;
                        } | undefined;
                        map_value?: any | undefined;
                        list_value?: {
                            values?: any[] | undefined;
                        } | undefined;
                        type_value?: string | undefined;
                    } | undefined;
                    value?: {
                        null_value?: dependency_2.google.protobuf.NullValue | undefined;
                        bool_value?: boolean | undefined;
                        int64_value?: number | undefined;
                        uint64_value?: number | undefined;
                        double_value?: number | undefined;
                        string_value?: string | undefined;
                        bytes_value?: Uint8Array | undefined;
                        enum_value?: {
                            type?: string | undefined;
                            value?: number | undefined;
                        } | undefined;
                        object_value?: {
                            type_url?: string | undefined;
                            value?: Uint8Array | undefined;
                        } | undefined;
                        map_value?: any | undefined;
                        list_value?: {
                            values?: any[] | undefined;
                        } | undefined;
                        type_value?: string | undefined;
                    } | undefined;
                }[] | undefined;
            } | undefined;
            list_value?: {
                values?: any[] | undefined;
            } | undefined;
            type_value?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Value;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Value;
    }
    class EnumValue extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            type?: string;
            value?: number;
        });
        get type(): string;
        set type(value: string);
        get value(): number;
        set value(value: number);
        static fromObject(data: {
            type?: string;
            value?: number;
        }): EnumValue;
        toObject(): {
            type?: string | undefined;
            value?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): EnumValue;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): EnumValue;
    }
    class ListValue extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            values?: Value[];
        });
        get values(): Value[];
        set values(value: Value[]);
        static fromObject(data: {
            values?: ReturnType<typeof Value.prototype.toObject>[];
        }): ListValue;
        toObject(): {
            values?: {
                null_value?: dependency_2.google.protobuf.NullValue | undefined;
                bool_value?: boolean | undefined;
                int64_value?: number | undefined;
                uint64_value?: number | undefined;
                double_value?: number | undefined;
                string_value?: string | undefined;
                bytes_value?: Uint8Array | undefined;
                enum_value?: {
                    type?: string | undefined;
                    value?: number | undefined;
                } | undefined;
                object_value?: {
                    type_url?: string | undefined;
                    value?: Uint8Array | undefined;
                } | undefined;
                map_value?: {
                    entries?: {
                        key?: any | undefined;
                        value?: any | undefined;
                    }[] | undefined;
                } | undefined;
                list_value?: {
                    values?: any[] | undefined;
                } | undefined;
                type_value?: string | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListValue;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ListValue;
    }
    class MapValue extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            entries?: MapValue.Entry[];
        });
        get entries(): MapValue.Entry[];
        set entries(value: MapValue.Entry[]);
        static fromObject(data: {
            entries?: ReturnType<typeof MapValue.Entry.prototype.toObject>[];
        }): MapValue;
        toObject(): {
            entries?: {
                key?: {
                    null_value?: dependency_2.google.protobuf.NullValue | undefined;
                    bool_value?: boolean | undefined;
                    int64_value?: number | undefined;
                    uint64_value?: number | undefined;
                    double_value?: number | undefined;
                    string_value?: string | undefined;
                    bytes_value?: Uint8Array | undefined;
                    enum_value?: {
                        type?: string | undefined;
                        value?: number | undefined;
                    } | undefined;
                    object_value?: {
                        type_url?: string | undefined;
                        value?: Uint8Array | undefined;
                    } | undefined;
                    map_value?: {
                        entries?: any[] | undefined;
                    } | undefined;
                    list_value?: {
                        values?: any[] | undefined;
                    } | undefined;
                    type_value?: string | undefined;
                } | undefined;
                value?: {
                    null_value?: dependency_2.google.protobuf.NullValue | undefined;
                    bool_value?: boolean | undefined;
                    int64_value?: number | undefined;
                    uint64_value?: number | undefined;
                    double_value?: number | undefined;
                    string_value?: string | undefined;
                    bytes_value?: Uint8Array | undefined;
                    enum_value?: {
                        type?: string | undefined;
                        value?: number | undefined;
                    } | undefined;
                    object_value?: {
                        type_url?: string | undefined;
                        value?: Uint8Array | undefined;
                    } | undefined;
                    map_value?: {
                        entries?: any[] | undefined;
                    } | undefined;
                    list_value?: {
                        values?: any[] | undefined;
                    } | undefined;
                    type_value?: string | undefined;
                } | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MapValue;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): MapValue;
    }
    namespace MapValue {
        class Entry extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                key?: Value;
                value?: Value;
            });
            get key(): Value;
            set key(value: Value);
            get has_key(): boolean;
            get value(): Value;
            set value(value: Value);
            get has_value(): boolean;
            static fromObject(data: {
                key?: ReturnType<typeof Value.prototype.toObject>;
                value?: ReturnType<typeof Value.prototype.toObject>;
            }): Entry;
            toObject(): {
                key?: {
                    null_value?: dependency_2.google.protobuf.NullValue | undefined;
                    bool_value?: boolean | undefined;
                    int64_value?: number | undefined;
                    uint64_value?: number | undefined;
                    double_value?: number | undefined;
                    string_value?: string | undefined;
                    bytes_value?: Uint8Array | undefined;
                    enum_value?: {
                        type?: string | undefined;
                        value?: number | undefined;
                    } | undefined;
                    object_value?: {
                        type_url?: string | undefined;
                        value?: Uint8Array | undefined;
                    } | undefined;
                    map_value?: {
                        entries?: {
                            key?: any | undefined;
                            value?: any | undefined;
                        }[] | undefined;
                    } | undefined;
                    list_value?: {
                        values?: any[] | undefined;
                    } | undefined;
                    type_value?: string | undefined;
                } | undefined;
                value?: {
                    null_value?: dependency_2.google.protobuf.NullValue | undefined;
                    bool_value?: boolean | undefined;
                    int64_value?: number | undefined;
                    uint64_value?: number | undefined;
                    double_value?: number | undefined;
                    string_value?: string | undefined;
                    bytes_value?: Uint8Array | undefined;
                    enum_value?: {
                        type?: string | undefined;
                        value?: number | undefined;
                    } | undefined;
                    object_value?: {
                        type_url?: string | undefined;
                        value?: Uint8Array | undefined;
                    } | undefined;
                    map_value?: {
                        entries?: {
                            key?: any | undefined;
                            value?: any | undefined;
                        }[] | undefined;
                    } | undefined;
                    list_value?: {
                        values?: any[] | undefined;
                    } | undefined;
                    type_value?: string | undefined;
                } | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Entry;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): Entry;
        }
    }
}
